export type CarRecord = {
  year: number;
  model: string;
  wikiTitle: string;
  confidence: 'ranked' | 'proxy';
};

export const europeanBestSellers: CarRecord[] = [
  { year: 1926, model: 'Ford Model T', wikiTitle: 'Ford Model T', confidence: 'proxy' },
  { year: 1927, model: 'Ford Model T', wikiTitle: 'Ford Model T', confidence: 'proxy' },
  { year: 1928, model: 'Ford Model T', wikiTitle: 'Ford Model T', confidence: 'proxy' },
  { year: 1929, model: 'Ford Model T', wikiTitle: 'Ford Model T', confidence: 'proxy' },
  { year: 1930, model: 'Austin 7', wikiTitle: 'Austin 7', confidence: 'proxy' },
  { year: 1931, model: 'Austin 7', wikiTitle: 'Austin 7', confidence: 'proxy' },
  { year: 1932, model: 'Austin 7', wikiTitle: 'Austin 7', confidence: 'proxy' },
  { year: 1933, model: 'Ford Model Y', wikiTitle: 'Ford Model Y', confidence: 'proxy' },
  { year: 1934, model: 'Ford Model Y', wikiTitle: 'Ford Model Y', confidence: 'proxy' },
  { year: 1935, model: 'Ford Model Y', wikiTitle: 'Ford Model Y', confidence: 'proxy' },
  { year: 1936, model: 'Ford Popular', wikiTitle: 'Ford Popular', confidence: 'proxy' },
  { year: 1937, model: 'Ford Popular', wikiTitle: 'Ford Popular', confidence: 'proxy' },
  { year: 1938, model: 'Ford Popular', wikiTitle: 'Ford Popular', confidence: 'proxy' },
  { year: 1939, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1940, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1941, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1942, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1943, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1944, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1945, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1946, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1947, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1948, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1949, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1950, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1951, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1952, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1953, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1954, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1955, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1956, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1957, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1958, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1959, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1960, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1961, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1962, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1963, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1964, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1965, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1966, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1967, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1968, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1969, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1970, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1971, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'proxy' },
  { year: 1972, model: 'Volkswagen Beetle', wikiTitle: 'Volkswagen Beetle', confidence: 'ranked' },
  { year: 1973, model: 'Fiat 127', wikiTitle: 'Fiat 127', confidence: 'ranked' },
  { year: 1974, model: 'Fiat 127', wikiTitle: 'Fiat 127', confidence: 'ranked' },
  { year: 1975, model: 'Fiat 127', wikiTitle: 'Fiat 127', confidence: 'ranked' },
  { year: 1976, model: 'Fiat 127', wikiTitle: 'Fiat 127', confidence: 'ranked' },
  { year: 1977, model: 'Fiat 127', wikiTitle: 'Fiat 127', confidence: 'ranked' },
  { year: 1978, model: 'Fiat 127', wikiTitle: 'Fiat 127', confidence: 'ranked' },
  { year: 1979, model: 'Renault 5', wikiTitle: 'Renault 5', confidence: 'ranked' },
  { year: 1980, model: 'Renault 5', wikiTitle: 'Renault 5', confidence: 'ranked' },
  { year: 1981, model: 'Renault 5', wikiTitle: 'Renault 5', confidence: 'ranked' },
  { year: 1982, model: 'Renault 5', wikiTitle: 'Renault 5', confidence: 'ranked' },
  { year: 1983, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1984, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1985, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1986, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1987, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1988, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1989, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1990, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1991, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1992, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1993, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1994, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1995, model: 'Fiat Punto', wikiTitle: 'Fiat Punto', confidence: 'ranked' },
  { year: 1996, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1997, model: 'Fiat Punto', wikiTitle: 'Fiat Punto', confidence: 'ranked' },
  { year: 1998, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 1999, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2000, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2001, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2002, model: 'Peugeot 206', wikiTitle: 'Peugeot 206', confidence: 'ranked' },
  { year: 2003, model: 'Peugeot 206', wikiTitle: 'Peugeot 206', confidence: 'ranked' },
  { year: 2004, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2005, model: 'Opel Astra', wikiTitle: 'Opel Astra', confidence: 'ranked' },
  { year: 2006, model: 'Opel Astra', wikiTitle: 'Opel Astra', confidence: 'ranked' },
  { year: 2007, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2008, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2009, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2010, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2011, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2012, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2013, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2014, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2015, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2016, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2017, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2018, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2019, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2020, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2021, model: 'Volkswagen Golf', wikiTitle: 'Volkswagen Golf', confidence: 'ranked' },
  { year: 2022, model: 'Peugeot 208', wikiTitle: 'Peugeot 208', confidence: 'ranked' },
  { year: 2023, model: 'Tesla Model Y', wikiTitle: 'Tesla Model Y', confidence: 'ranked' },
  { year: 2024, model: 'Dacia Sandero', wikiTitle: 'Dacia Sandero', confidence: 'ranked' },
  { year: 2025, model: 'Dacia Sandero', wikiTitle: 'Dacia Sandero', confidence: 'ranked' },
];

export function carForBirthYear(year: number): CarRecord {
  return europeanBestSellers.find((car) => car.year === year) ?? europeanBestSellers[0];
}
